apiVersion: v1
type: cli/v1
name: values
version: "0.0.1"
runtime: subprocess
sourceURL: https://github.com/brahmlower/helm-values
config:
  shortHelp: Schema and docs generator for Helm values
runtimeConfig:
  platformCommand:
    - command: ${HELM_PLUGIN_DIR}/helm-values

# legacy metadata, needed for artifacthub
description:
  Schema and docs generator for Helm values
