apiVersion: v1
type: cli/v1
name: values
version: "0.0.1"
runtime: subprocess
sourceURL: https://github.com/brahmlower/helm-values
config:
  shortHelp: Schema and docs generator for Helm values
runtimeConfig:
  platformCommand:
    - os: darwin
      command: ${HELM_PLUGIN_DIR}/helm-values
    - os: linux
      command: ${HELM_PLUGIN_DIR}/helm-values
    - os: windows
      command: ${HELM_PLUGIN_DIR}/helm-values.exe
  platformHooks: # Configure plugin lifecycle hooks based on the platform
    install: # Install lifecycle commands
      - os: darwin
        arch: arm64
        command: echo "hello world"
      - os: darwin
        arch: x86
        command: ${HELM_PLUGIN_DIR}/helm-values
      - os: linux
        arch: arm64
        command: ${HELM_PLUGIN_DIR}/helm-values
      - os: linux
        arch: i386
        command: ${HELM_PLUGIN_DIR}/helm-values
      - os: linux
        arch: x86
        command: ${HELM_PLUGIN_DIR}/helm-values
      - os: windows
        arch: arm64
        command: ${HELM_PLUGIN_DIR}/helm-values.exe
      - os: windows
        arch: i386
        command: ${HELM_PLUGIN_DIR}/helm-values.exe
      - os: windows
        arch: x86
        command: ${HELM_PLUGIN_DIR}/helm-values.exe

# legacy metadata, needed for artifacthub
description:
  Schema and docs generator for Helm values
