# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/helm-values {{.CLI_ARGS}}

  build:bin:
    desc: Build production binary
    cmds:
      - goreleaser build --clean --snapshot

  build:plugin:
    desc: Build release artifacts
    cmds:
      # build the binaries
      - goreleaser build --clean {{.CLI_ARGS}}
      # render the plugin file
      - sed "s/VERSION/$(git describe --tags --abbrev=0)/" plugin.yaml.tmpl > ./dist/helm-values/plugin.yaml
      # package the plugin
      - helm plugin package -d ./dist/ ./dist/helm-values/. --sign=false

  reinstall:
    desc: Reinstall the plugin locally
    cmds:
      - helm plugin uninstall values || true
      - helm plugin install ./dist/values-$(git describe --tags --abbrev=0).tgz

  test:
    desc: Run all tests
    cmds:
      - task: test:unit
      - task: test:pre-commit

  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./pkg/...
      - go test ./cmd/...

  test:pre-commit:
    desc: Run pre-commit hook tests
    dir: ./tests/pre-commit
    cmds:
      - bats ./tests.bats

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist
