version: '3'

tasks:
  build:bin:
    desc: Build production binary
    cmds:
      - goreleaser build --clean --snapshot

  build:plugin:
    desc: Build release artifacts
    cmds:
      - goreleaser build --clean {{.CLI_ARGS}}
      - cp ./plugin.yaml ./dist/helm-values/.
      - helm plugin package -d ./dist/ ./dist/helm-values/. --sign=false

  test:
    desc: Run unit tests
    cmds:
      - go test ./internal/...
      - go test ./pkg/...
      - go test ./cmd/...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist
