name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7.0.0

      - name: Install GoReleaser
        run: sudo snap install --classic goreleaser

      - name: Install Helm
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

      - name: Install taskfile
        run: |
          sudo snap install task --classic

      - name: Configure GPG key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import
          key_id=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ { print $5; exit }')
          gpg --export-secret-keys "$key_id" > "$RUNNER_TEMP/signing-keyring.gpg"
          echo "GPG_KEY_ID=$key_id" >> "$GITHUB_ENV"
          echo "GPG_KEYRING=$RUNNER_TEMP/signing-keyring.gpg" >> "$GITHUB_ENV"
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Build
        run: |
          task build:plugin

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4.8.0
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Release
        uses: softprops/action-gh-release@v3.0.2
        if: github.ref_type == 'tag'
        with:
          draft: true
          body_path: CHANGES.md
          files: |
            ./dist/values-*.tgz
            ./dist/values-*.tgz.prov
