name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6

      - name: Install GoReleaser
        run: sudo snap install --classic goreleaser

      - name: Install Helm
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

      - name: Install taskfile
        run: |
          sudo snap install task --classic

      # Soon 👀
      # - name: Configure GPG Key
      #   run: |
      #     echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      #   env:
      #     GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Build
        run: |
          task build:plugin

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: ./dist/values-*.tgz
