name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7.0.1

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: v2.13.2

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7.0.1

      - name: Install taskfile
        run: sudo snap install task --classic

      - name: Run unit tests
        run: task test:unit

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install taskfile
        run: sudo snap install task --classic

      - name: Install GoReleaser
        run: sudo snap install --classic goreleaser

      - name: Install pre-commit dependencies
        run: |
          sudo snap install helm --classic
          sudo npm install -g bats
          sudo npm install -g https://github.com/ztombol/bats-assert
          sudo npm install -g https://github.com/ztombol/bats-support
          pip install pre-commit

      - name: Install the plugin
        run: |
          task build:plugin -- --snapshot
          task reinstall

      - name: Run e2e tests
        run: task test:e2e
