name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6

      - name: Install taskfile
        run: sudo snap install task --classic

      - name: Run unit tests
        run: task test:unit

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install taskfile
        run: sudo snap install task --classic

      - name: Install GoReleaser
        run: sudo snap install --classic goreleaser

      - name: Install pre-commit dependencies
        run: |
          sudo snap install helm --classic
          sudo npm install -g bats
          sudo npm install -g https://github.com/ztombol/bats-assert
          sudo npm install -g https://github.com/ztombol/bats-support
          pip install pre-commit

      - name: Install the plugin
        run: |
          task build:plugin -- --snapshot
          task reinstall

      - name: Run pre-commit hook tests
        run: task test:pre-commit
